name: Deploy Server with New Model

on:
  workflow_run:
    workflows: ["Train ML Model"]
    types:
      - completed
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout server code
      uses: actions/checkout@v3
      with:
        path: server

    - name: Download model artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        path: server/models  # place into server/models directory

    - name: Trigger Railway Deploy
      run: |
        curl -X POST https://backboard.railway.app/project/${{ secrets.RAILWAY_PROJECT_ID }}/deploy \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}"
