name: Deploy FastAPI to Railway with latest model

on:
  push:
    paths:
      - 'server/**'
    branches: [main, master, feature/merge_deployment]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Railway Deploy
      run: |
        curl -X POST https://backboard.railway.app/project/YOUR_PROJECT_ID/deploy \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}"
